# Generated by Django 3.0.4 on 2020-03-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('car',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cars.Car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
        ),
    ]
