# Generated by Django 3.0.4 on 2020-05-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20200509_2348'),
        ('tasks', '0004_auto_20200503_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Person',
                                    verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tasks', to='core.Person', verbose_name='Person'),
        ),
    ]
