# Generated by Django 2.2.4 on 2019-08-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_auto_20190830_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
