# Generated by Django 2.2.4 on 2019-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0005_task_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
