# Generated by Django 2.2.4 on 2019-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0006_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City'),
        ),
    ]
