# Generated by Django 2.2.4 on 2019-11-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0007_auto_20190830_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
    ]
