# Generated by Django 3.0.4 on 2020-05-09 20:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitable_tasks', core.models.ChoiceArrayField(base_field=models.CharField(max_length=15),
                                                                choices=[(1, 'Regular cleaning and check'),
                                                                         (2, 'Big cleaning and check'),
                                                                         (3, 'Service check / Oil change'), (4, 'STK'),
                                                                         (5, 'Tyres change'), (99, 'Other')],
                                                                max_length=15, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
