# Generated by Django 3.0.7 on 2020-06-12 22:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0008_auto_20200530_2246'),
        ('core', '0001_squashed_0009_auto_20200509_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cars.City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='suitable_tasks',
            field=core.models.ChoiceArrayField(base_field=models.IntegerField(
                choices=[(1, 'Regular cleaning and check'), (2, 'Big cleaning and check'),
                         (3, 'Service check / Oil change'), (4, 'STK'), (5, 'Tyres change'), (99, 'Other')]),
                                               blank=True, size=None),
        ),
    ]
