# Generated by Django 3.0.4 on 2020-05-09 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20200509_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='suitable_tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                choices=[(1, 'Regular cleaning and check'), (2, 'Big cleaning and check'),
                         (3, 'Service check / Oil change'), (4, 'STK'), (5, 'Tyres change'), (99, 'Other')],
                max_length=15), max_length=15, size=None),
        ),
    ]
