# Generated by Django 3.0.4 on 2020-05-09 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200509_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='suitable_tasks',
            field=core.models.ChoiceArrayField(base_field=models.IntegerField(
                choices=[(1, 'Regular cleaning and check'), (2, 'Big cleaning and check'),
                         (3, 'Service check / Oil change'), (4, 'STK'), (5, 'Tyres change'), (99, 'Other')]), size=1),
        ),
    ]
