# Generated by Django 3.0.4 on 2020-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0006_auto_20200503_1121'),
        ('core', '0007_auto_20200509_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cities',
            field=models.ManyToManyField(to='cars.City'),
        ),
    ]
