# Generated by Django 2.2.3 on 2019-08-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, unique=True)),
                ('car_id', models.DecimalField(decimal_places=0, max_digits=5, unique=True)),
                ('car_next_inspection_date', models.DateField()),
                ('car_next_inspection_km', models.DecimalField(decimal_places=0, max_digits=10)),
                ('car_next_oil_date', models.DateField()),
                ('car_next_oil_km', models.DecimalField(decimal_places=0, max_digits=10)),
                ('car_last_check', models.DateTimeField()),
                ('car_note', models.CharField(blank=True, max_length=1024)),
                ('car_city',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='cars.City')),
            ],
        ),
    ]
