# Generated by Django 3.0.4 on 2020-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_dirtiness',
            field=models.IntegerField(blank=True,
                                      choices=[(1, 'Fine, looks good'), (2, 'Few stains, still good enough'),
                                               (3, 'Car needs wet cleaning. Really.')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_next_stk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_tyres',
            field=models.IntegerField(blank=True, choices=[(1, 'All year'), (2, 'Summer'), (3, 'Winter')], default=1,
                                      null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_last_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
