# Generated by Django 2.2.3 on 2019-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_car_car_actual_driven_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_last_check',
            field=models.DateField(),
        ),
    ]
