# Generated by Django 3.0.4 on 2020-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_auto_20200422_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_actual_driven_kms',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Driven KMs'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_dirtiness',
            field=models.IntegerField(blank=True,
                                      choices=[(1, 'Fine, looks good'), (2, 'Few stains, still good enough'),
                                               (3, 'Car needs wet cleaning. Really.')], default=1,
                                      help_text='Applies just for big/wet cleaning.', null=True,
                                      verbose_name='Need of wet cleaning'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.DecimalField(decimal_places=0, help_text='ID for finding car in Zemtu, Convadis,...',
                                      max_digits=5, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_last_check',
            field=models.DateField(blank=True, null=True, verbose_name='Last check'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_next_inspection_date',
            field=models.DateField(verbose_name='Next inspection date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_next_inspection_km',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Next inspection KMs'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_next_oil_date',
            field=models.DateField(verbose_name='Next oil change date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_next_oil_km',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Next oil change KMs'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_next_stk_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next STK date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_note',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_tyres',
            field=models.IntegerField(blank=True, choices=[(1, 'All year'), (2, 'Summer'), (3, 'Winter')], default=1,
                                      help_text='If seasonal tyre change is needed, task will be planned', null=True,
                                      verbose_name='Actual Tyres'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
