# Generated by Django 3.0.4 on 2020-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0003_auto_20200422_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Use to deactivate car. Deactivated cars do not get automatic tasks and reminders.',
                                      verbose_name='Active'),
        ),
    ]
