# Generated by Django 2.2.4 on 2019-08-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0004_auto_20190821_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_note',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
