# Generated by Django 2.2.4 on 2019-08-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0005_auto_20190827_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.City',
                                    verbose_name='City'),
        ),
    ]
