# Generated by Django 3.0.4 on 2020-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0006_auto_20200503_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_note',
            field=models.TextField(blank=True,
                                   help_text='This is just for internal notes and tips.\n If you want to report somedamage or problem, please inform responsible person.',
                                   max_length=1024, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='car_note',
            field=models.TextField(blank=True,
                                   help_text='This is just for internal notes and tips.\n If you want to report somedamage or problem, please inform responsible person.',
                                   max_length=1024, verbose_name='Notes'),
        ),
    ]
