# Generated by Django 3.0.7 on 2020-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0008_auto_20200530_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='car_routine_check_interval',
            field=models.IntegerField(default=20, help_text='Apply only to cars in this city.',
                                      verbose_name='Days between checks'),
        ),
        migrations.AddField(
            model_name='city',
            name='car_task_due_days',
            field=models.IntegerField(default=15, help_text='Apply only to cars in this city.',
                                      verbose_name='Days to complete generated task'),
        ),
    ]
